# https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup
ec_sales: # dbt_demo name. This is where dbt looks for from dbt_project.yml -> find the named profile here. Can also be overwritten by dbt run --profiles. See dbt run --help for more info
  target: jaffle_sql # default target for profile, points to 1 of the output below # define target in dbt CLI via --target
  outputs:
    threads: 1
    location: US
    jaffle_sql:
      type: bigquery
      method: service-account
      project: dsai-g3-m2-project
      dataset: brazilian_ecommerce_sales
      retries: 2
      keyfile: ../dsai-g3-m2-project-4ec07ed7098f.json
  config:
    send_anonymous_usage_stats: False
e_commerce_dbt:
  outputs:
    dev:
      dataset: brazilian_ecommerce_sales
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "/Users/david/Documents/Documents - David\u2019s MacBook Pro/NTU_DSAI/Materials/Module2/Project/dsai-g3-m2-project-4ec07ed7098f.json"
      location: US
      method: service-account
      priority: interactive
      project: dsai-g3-m2-project
      threads: 4
      type: bigquery
  target: dev