
version: 2

models:
  - name: dim_products
    description: "Dimension table for products"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: product_category_name
        tests:
          - not_null
      - name: product_name_length
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
              max_value: 100  # Add a reasonable upper limit
      - name: product_description_length
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
              max_value: 5000  # Add a reasonable upper limit
      - name: product_photos_qty
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
              max_value: 30  # Add a reasonable upper limit
      - name: product_weight_g
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
              strictly: True # Values must be greater than 0
      - name: product_volume_cm3
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
              strictly: True # Values must be greater than 0
  - name: dim_customers
    description: "Dimension table for customers"
    columns:
      - name: customer_id
        description: "Customer ID. The primary key for this table"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string
      - name: customer_unique_id
        description: "Customer unique ID"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: string
      - name: customer_zip_code_prefix
        description: "Customer zip code prefix"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 00000
              max_value: 99999
      - name: customer_city
        description: "Customer city"
        tests:
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 1
              max_value: 256
      - name: customer_state
        description: "Customer state"
        tests:
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 1
              max_value: 2
  - name: dim_sellers
    description: "Dimension table for seller"
    columns:
      - name: seller_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: seller_zip_code_prefix
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 00000
              max_value: 99999
      - name: seller_city
        tests:
          - not_null
      - name: seller_state
        tests:
          - not_null
      - name: seller_total_order_revenue
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null

      
