
version: 2

models:
  - name: dim_products
    description: "Dimension table for products"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_name_length
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_description_length
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_photos_qty
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_weight_g
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_length_cm
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_height_cm
        description: "The primary key for this table"
        tests:
          - not_null
      - name: product_width_cm
        description: "The primary key for this table"
        tests:
          - not_null
  - name: dim_customers
    description: "Dimension table for customers"
    columns:
      - name: customer_id
        description: "Customer ID. The primary key for this table"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Customer unique ID"
        tests:
          - unique
          - not_null
      - name: customer_zip_code_prefix
        description: "Customer zip code prefix"
        tests:
          - not_null
      - name: customer_city
        description: "Customer city"
        tests:
          - not_null
      - name: customer_state
        description: "Customer state"
        tests:
          - not_null
      
