
version: 2

models:

  - name: dim_seller
    description: "Dimension table for seller"
    columns:
      - name: seller_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: seller_zip_code_prefix
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 00000
              max_value: 99999
      - name: seller_city
        tests:
          - not_null
      - name: seller_state
        tests:
          - not_null
      - name: seller_total_order_revenue
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
          - not_null
     
      
